version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    links:
      - guacamole
    restart: unless-stopped
    environment:
      DOMAINS: "example.net -> http://guacamole:8080"
      STAGE: "production"
    networks:
      - guacamole_network

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacdb
      POSTGRES_PASSWORD: guacpw
      POSTGRES_USER: guacuser
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - guacamole_network

  guacd:
    image: guacamole/guacd:latest
    restart: unless-stopped
    volumes:
      - ./guacd/ipaexg.ttf:/usr/share/fonts/ipaexg.ttf:ro
      - ./guacd/log:/var/log/guacamole/
    networks:
      - guacamole_network

  guacamole:
    image: guacamole/guacamole:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacdb
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: guacpw
      POSTGRES_USER: guacuser
      GUACAMOLE_HOME: /etc/guacamole
    volumes:
      - ./guacamole:/etc/guacamole
    depends_on:
      - postgres
      - guacd
    networks:
      - guacamole_network

networks:
  guacamole_network:
    driver: bridge
